/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientDesktop.java
 *
 * Created on Oct 27, 2009, 4:21:52 PM
 */

package com.server.gui;

import com.server.conn.ClientManager;
import com.server.conn.ConnectionManager;
import com.server.utils.SettingsConstatnts;
import javax.swing.ImageIcon;

/**
 *
 * @author Administrator
 */
public class ClientDesktop extends javax.swing.JFrame {

    /** Creates new form ClientDesktop */
    private String ipAddress = "";
    public ClientDesktop() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        desktopLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        desktopLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desktopLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                desktopLabelMouseReleased(evt);
            }
        });
        desktopLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                desktopLabelMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                desktopLabelMouseMoved(evt);
            }
        });
        desktopLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                desktopLabelKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                desktopLabelKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here
        ConnectionManager.desktopManager.closeFullScreen(ipAddress);
         Object obj = ConnectionManager.connectedClients.get(ipAddress);
            if (obj != null && obj instanceof ClientManager) {
                ClientManager clientManager = (ClientManager) obj;
                clientManager.sendRequestToClient("TIME:" + SettingsConstatnts.CAPTURING_INRVL);
            }
        //System.err.println("ffffffffffffffffffffffffffffffff");
    }//GEN-LAST:event_formWindowClosing

    private void desktopLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopLabelMouseMoved
        // TODO add your handling code here:
        ConnectionManager.desktopManager.mouseMoved(evt.getX(), evt.getY(), ipAddress);
    }//GEN-LAST:event_desktopLabelMouseMoved

    private void desktopLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopLabelMousePressed
        // TODO add your handling code here:
        ConnectionManager.desktopManager.mousePressed(ipAddress, evt);
    }//GEN-LAST:event_desktopLabelMousePressed

    private void desktopLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopLabelMouseReleased
        // TODO add your handling code here:
        ConnectionManager.desktopManager.mouseReleased(ipAddress,evt);
    }//GEN-LAST:event_desktopLabelMouseReleased

    private void desktopLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopLabelMouseDragged
        // TODO add your handling code here:
        ConnectionManager.desktopManager.mouseMoved(evt.getX(), evt.getY(), ipAddress);
    }//GEN-LAST:event_desktopLabelMouseDragged

    private void desktopLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desktopLabelKeyPressed
       ConnectionManager.desktopManager.keyPressed(evt.getKeyCode(), ipAddress);
    }//GEN-LAST:event_desktopLabelKeyPressed

    private void desktopLabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desktopLabelKeyReleased
       ConnectionManager.desktopManager.keyReleased(evt.getKeyCode(), ipAddress);
    }//GEN-LAST:event_desktopLabelKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       ConnectionManager.desktopManager.keyPressed(evt.getKeyCode(), ipAddress);
    }//GEN-LAST:event_formKeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
       ConnectionManager.desktopManager.keyReleased(evt.getKeyCode(), ipAddress);
    }//GEN-LAST:event_formKeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientDesktop().setVisible(true);
            }
        });
    }
    public void setDesktopImage(ImageIcon image){
        desktopLabel.setIcon(image);
        desktopLabel.updateUI();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel desktopLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
        this.setTitle(ipAddress);
    }

}
